'use strict';

(function () {
  window.ClassNames = {
    POPUP_TYPE: '.popup__type',
    POPUP_PHOTOS: '.popup__photos',
    POPUP_PHOTO: '.popup__photo',
    POPUP_FEATURE: '.popup__feature',
    POPUP_FEATURES: '.popup__features',
    POPUP_TITLE: '.popup__title',
    POPUP_ADDRESS: '.popup__text--address',
    POPUP_PRICE: '.popup__text--price',
    POPUP_CAPACITY: '.popup__text--capacity',
    POPUP_TIME: '.popup__text--time',
    POPUP_DESCRIPTION: '.popup__description',
    POPUP_AVATAR: '.popup__avatar',
    POPUP_CLOSE: '.popup__close',
    FILTERS_CONTAINER: '.map__filters-container',
    MAP_OVERLAY: '.map__overlay',
    MAP_PINS: '.map__pins',
    MAP_PIN: '.map__pin',
    MAP_PIN_ACTIVE: '.map__pin--active',
    MAP_CARD: '.map__card',
    MAP: '.map',
    MAP_FADED: '.map--faded',
    HIDDEN: '.hidden',
    AD_FORM: '.ad-form',
    AD_FORM_DISABLED: '.ad-form--disabled',
    MAP_FILTERS: '.map__filters',
    MAIN_PIN: '.map__pin--main',
    AD_FORM_SUBMIT: '.ad-form__submit',
    RESET_BUTTON: '.ad-form__reset',
    SUCCESS: '.success',
    ERROR: '.error',
    ERROR_BUTTON: '.error__button',
    CHECKBOX_FEATURES_WRAPPER: '.map__features',
    AD_FORM_FIELD: '.ad-form__field',
    AD_FORM_UPLOAD: '.ad-form__upload',
    AD_FORM_PHOTO: '.ad-form__photo',
    AD_FORM_PHOTO_NEW: '.ad-form__photo--new',
    AD_FORM_AVATAR_PREVIEW: '.ad-form-header__preview',
    AD_FORM_HOUSING_PREVIEW_CONTAINER: '.ad-form__photo-container'
  };
})();
